### ISSUE TITLE
Deep reference in models doesn't really work

### ISSUE THREAD

**Issue by neo** [cyclosproject/ng-swagger-gen#109]
For example:
```yaml
definitions:
  Brand:
    type: 'object'
    properties:
      key:
        type: 'string'
      name:
        type: 'string'
  Submission:
    type: 'object'
    properties:
      key:
        type: 'string'
      brand:
        $ref: '#/definitions/Brand/properties/key'
```
Output:
```TypeScript
/* tslint:disable */
export interface Submission {
  key?: string;
  brand?: Key; // <- which throws an error
}
```
Expected output:
```TypeScript
/* tslint:disable */
import { Brand } from './brand';

export interface Submission {
  key?: string;
  brand?: Brand['key'];
}
```

**Comment by luisfpg** [comment]
I'd say this is out of scope for ng-swagger-gen. We don't intend to implement every single aspect of the Swagger specification.
Of course, we welcome contributions to implement such corner cases.

**Comment by mvatanasovFMI** [comment]
@luisfpg Hello i would like to ask you do you have some problem when you try to geneterate "TablePage`1" this model it generate Mode TablePage1 but later in the returns object it generates TablePage601

**Comment by luisfpg** [comment]
See #254
