### ISSUE TITLE
Path parameters with underscore generates invalid classes

### ISSUE THREAD

**Issue by matodrobec** [cyclosproject/ng-swagger-gen#110]
Hello,

my swagger schema json use parameter names with underscore `test_key`. Output servise looks like
```
let req = new HttpRequest<any>(
      'GET',
      this.rootUrl + `/application/1/test.json/${params.test_key}`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });
```
and but params has camelCase `testKey` 
```
export interface GetTestParams {

    /**
     * Interne ID
     */
    testKey: string;
```
 
Is possible to so use original names instead of camelCase?

**Comment by luisfpg** [comment]
By the project standards, the parameter should be camel case, but the bug is using the original name when appending to the URL.
Will be fixed soon.
