### ISSUE TITLE
No exported enum

### ISSUE THREAD

**Issue by ThomasBoersma** [cyclosproject/ng-swagger-gen#111]
Hi,

I'm having a problem with not getting exported enums. I retrieve, instead a literal of strings:

`type?: 'DrivingLicence' | 'Passport' | 'IdentityCard';`

But I was hoping that I get an enum class with these types. My swagger definition is stated as follow:

```
definitions: { 
...
IdentityDocument: {
  type: "object",
  properties: {
    number: {
      type: "string"
    },
  type: {
    enum: [
      "DrivingLicence",
      "Passport",
      "IdentityCard"
    ],
      type: "string"
    }
  }
},
...
}
```

Is there a feature that I can use, or change something in the swagger.json?

**Comment by luisfpg** [comment]
That's how inline enums are implemented in ng-swagger-gen.
It never generates actual enums. When the project started, TypeScript still didn't support enums with string values.
However, for practical effects, in TypeScript it is mostly the same, as you'll get from your IDE (eg, VSCode) errors if using a literal that isn't allowed.
If you would use $ref instead to a model which is actually a enum, the resulting class will be the same: a type definition. However, in that case, it is also possible to generate constants for each value.

**Comment by KnutHaraldR** [comment]
My issue with this is that I want to iterate over the enum values, not sure how I can get a list of them if they only exist as a type restriction. Is it possible?

**Comment by luisfpg** [comment]
@KnutHaraldR If the enum is a top-level definitions, by default a module with the enum name is exported, and it has a values() method.
For embedded enums, there's no such support.

**Comment by jmwierzbicki** [comment]
Could somebody put example, how to make these enum modules? 
Im getting only this:
![image](https://user-images.githubusercontent.com/11833720/51379665-37235580-1b10-11e9-95c2-242e71cd178a.png)

and there are no enum with values() method generated, so im unable to import these values to my application.

**Comment by luisfpg** [comment]
Something like:
```json
{
...
  "schemas": {
    "MyEnum": {
      "type": "string",
      "enum": ["value1", "value2", "value3"]
    },
    "MyObject": {
      "type": "object",
      "properties": {
        "myEnum": {
          "$ref": "#/schemas/MyEnum"
        }
      }
    }
}
```

Then reference it as a regular type

In Swagger 2 you cannot have a reference in an operation parameter. But if you need such enum in a parameter, you can set `"x-type": "MyEnum"` and the generator will use that type.
