### ISSUE TITLE
With version 1.4 following minimal instructions angular/cli is throwing typescript compiler exception

### ISSUE THREAD

**Issue by gitschlonzo** [cyclosproject/ng-swagger-gen#115]
With version 1.3.x everything worked fine. With version 1.4 I now get an exception when executing ng serve.

You can easily reproduce the problem by following your own minimal example:
```
ng new petstore
cd petstore
npm install --save-dev ng-swagger-gen
node_modules/.bin/ng-swagger-gen -i http://petstore.swagger.io/v2/swagger.json
ng serve
```

This is the exception I get:

> ERROR in : Error: Debug Failure. False expression: should always get typenode
>     at typeToString (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:29274:22)
>     at reportRelationError (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36080:34)
>     at isRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36266:21)
>     at typeArgumentsRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36483:39)
>     at structuredTypeRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36726:38)
>     at recursiveTypeRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36564:64)
>     at isRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36236:38)
>     at checkTypeRelatedTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:36050:26)
>     at checkTypeAssignableTo (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:35735:20)
>     at checkReturnStatement (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:48405:25)
>     at checkSourceElement (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:49852:28)
>     at Object.forEach (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:1792:30)
>     at checkBlock (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:47521:20)
>     at checkSourceElement (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:49831:28)
>     at checkFunctionOrMethodDeclaration (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:47242:13)
>     at checkMethodDeclaration (D:\Chris\Visual Studio Code\Projects\petstore\node_modules\typescript\lib\typescript.js:46117:13)

And this is my package.json:

> {
>   "name": "petstore",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^6.1.0",
>     "@angular/common": "^6.1.0",
>     "@angular/compiler": "^6.1.0",
>     "@angular/core": "^6.1.0",
>     "@angular/forms": "^6.1.0",
>     "@angular/http": "^6.1.0",
>     "@angular/platform-browser": "^6.1.0",
>     "@angular/platform-browser-dynamic": "^6.1.0",
>     "@angular/router": "^6.1.0",
>     "core-js": "^2.5.4",
>     "rxjs": "~6.2.0",
>     "zone.js": "~0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.8.0",
>     "@angular/cli": "~6.2.7",
>     "@angular/compiler-cli": "^6.1.0",
>     "@angular/language-service": "^6.1.0",
>     "@types/jasmine": "~2.8.8",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/node": "~8.9.4",
>     "codelyzer": "~4.3.0",
>     "jasmine-core": "~2.99.1",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~3.0.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "~1.1.2",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "ng-swagger-gen": "^1.4.0",
>     "protractor": "~5.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.11.0",
>     "typescript": "~2.9.2"
>   }
> }

I solved the problem by rolling back to 1.3

**Comment by luisfpg** [comment]
Fixed on 1.4.1
