### ISSUE TITLE
Support for readonly property of generated types (in favor of immutability)

### ISSUE THREAD

**Issue by VhThomas** [cyclosproject/ng-swagger-gen#116]
I was wondering if it is a good idea to add configuration option to allow to have readonly properties on the  generated classes. This could be handy to support immutability.
We could always try to add our own mustache templates for this as well. Correct?

**Comment by luisfpg** [comment]
Swagger itself doesn't support any immutable-related configuration.
You can customize the templates, but I don't think you'll be able to easily do it via templates without having also changed the generator to send additional information to the template, as mustache is very limited when it comes to logic.
Anyway, this is out of scope for ng-swagger-gen.
