### ISSUE TITLE
Add support for partial files in the the templates folder

### ISSUE THREAD

**Issue by jmwierzbicki** [cyclosproject/ng-swagger-gen#121]
In my opinion this is great configuration option, but if used it needs to be filled with every template, while i only need to modify configuration.mustache to this:

```
/* tslint:disable */
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment'

/**
 * Global configuration for {{prefix}} services
 */
@Injectable({
  providedIn: 'root',
})
export class {{configurationClass}} {
  rootUrl: string = environment.baseApiUrl;
}

```

If overrided template directory contains only configuration, then cli returns:
> .\node_modules\.bin\ng-swagger-gen -c ng-swagger-gen.json
Error: TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)

It should use default files instead.

**Comment by luisfpg** [comment]
This can be an improvement, but you probably shouldn't customize the template just to set the `rootURL`.
Instead, you can try this: https://github.com/cyclosproject/ng-swagger-gen#specifying-the-root-url--web-service-endpoint.

**Comment by luisfpg** [comment]
Add support for reading default templates for files missing in the given templates folder.

**Comment by luisfpg** [comment]
Will not be implemented, due to lack of resources (not even the official swagger generators allow this).
However, https://github.com/cyclosproject/ng-openapi-gen was already developed with this in mind, and supports it.
