### ISSUE TITLE
FEATURE: Specify configuration file as command line argument

### ISSUE THREAD

**Issue by edoloughlin** [cyclosproject/ng-swagger-gen#13]
I want to generate separate API implementations based on two swagger files (on for NodeJS, another for Spring) into two separate API directories. I'd like to generate into src/api-spring and src/api-node. 

I need to use separate configuration files (ng-swagger-gen.json) for this so I have to mess around with renaming files. It would be easier if I could just specify `ng-swagger-gen -c spring-config.json` and `ng-swagger-gen -c node-config.json`

**Comment by dimitriy-k** [comment]
I was also missing that functionality, so forked the repo and added some features which we need (also stubs possibilities). If you are interested https://github.com/Vnumedia/ng-swagger-generate

**Comment by luisfpg** [comment]
@dimitriy-k Of course you're always welcome to fork, but why not contribute PR's back and keep using the upstream project instead?
Once you've forked, you'd have to continuously merge upstream changes if you want new bug fixes.
Anyway, this issue is a good use case and will be implemented soon.

**Comment by dimitriy-k** [comment]
@luisfpg you are right, I have merged it I think one time. But because of cloning forked repo, the upstream repo disappeared. Tried to add it again, but it have not worked. If have time I will try to do it again. It would be nice to keep it in think, you have done good work.
