### ISSUE TITLE
how to implement ETag headers 

### ISSUE THREAD

**Issue by dmushkov** [cyclosproject/ng-swagger-gen#138]
Rest API supports send ETag during response of Get and later use ETag in If-Match post request header. How to achieve that with this great tool?

**Comment by luisfpg** [comment]
There's no built-in support for ETag.
But, in terms of API description, you could declare the HTTP headers in a particular path, both the ETag response header and the If-Match / If-None-Match request parameters. The actual implementation would be server-side.
