### ISSUE TITLE
GET endpoint URL encode string (path?) parameter

### ISSUE THREAD

**Issue by KnutHaraldR** [cyclosproject/ng-swagger-gen#146]
I have a parameter for a GET method that I would use like this:

```
/search?query=
firstName==*frank*,middleName==*frank*,surname==*frank*,phoneNumber==*frank*,email==*frank*
```
The autogenerated code however, taking query as a parameter, converts it like this:

```
/search?query=
query%2CfirstName%3D%3D*frank*%2CmiddleName%3D%3D*frank*%2Csurname%3D%3D*frank*%2CphoneNumber%3D%3D*frank*%2Cemail%3D%3D*frank*%2C
```

I don't think there is a way to "inverse" URL encode, so the auto generated code will not be able to support my query parameter...

I am wondering if the problem may lie in that the endpoint uses a query rather than path parameter in it's definition though, if so and it was fixed, then maybe ng-swagger-gen would not URL-encode? OR should non-encoded query parameter be supported?

Here is the swagger definition of the endpoint:
`"/api/employees/search":{"get":{"tags":["employee-controller"],"summary":"searchEmployee","operationId":"searchEmployeeUsingGET","produces":["*/*"],"parameters":[{"name":"query","in":"query","description":"query","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/ResponseEntity"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}}`

**Comment by KnutHaraldR** [comment]
Note: The above URLs are from chrome's network tab log of sent requests. So maybe the problem is that URL encoding happens twice, and google chrome just display the unencoded URLs.

**Comment by luisfpg** [comment]
If you look at the generated `BaseService`, it has the `ParameterCodec`, which handle the encoding / decoding of parameters.
Actually, looking at it now, we have almost duplicated the `HttpUrlEncodingCodec` class, with some missing cases.
Can you, please, modify the generated BaseService, setting the `PARAMETER_CODEC` const and check if it works for your case? Something like:
```typescript
const PARAMETER_CODEC = new HttpUrlEncodingCodec()
```

**Comment by luisfpg** [comment]
Closing this due to lack of feedback
