### ISSUE TITLE
Switch to HttpClient

### ISSUE THREAD

**Issue by gerkirill** [cyclosproject/ng-swagger-gen#15]
Version 5.0.0 of Angular is released, and Http has been deprecated in favor of  HttpClient:

> Developers appreciated the new HttpClient (introduced in version 4.3)  so the team is now recommending HttpClient for all applications, and deprecating the previous @angular/http library.

Could you please update your library accordingly? thx.

**Comment by luisfpg** [comment]
The 0.9.0 version has been released.
There are some breaking changes. Please, check out https://github.com/cyclosproject/ng-swagger-gen/wiki/Upgrading-from-previous-versions-to-0.9 for more details.
