### ISSUE TITLE
Allow custom headers in service params

### ISSUE THREAD

**Issue by GeorgeKnap** [cyclosproject/ng-swagger-gen#153]
Hi, this is the example of one of generated service:
```
 getMockErrorIdResponse(id: string): Observable<StrictHttpResponse<Error2>> {
    let __params = this.newParams();
    let __headers = new HttpHeaders();
    let __body: any = null;

    let req = new HttpRequest<any>(
      'GET',
      this.rootUrl + `/mock/error/${id}`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });

    return this.http.request<any>(req).pipe(
      __filter(_r => _r instanceof HttpResponse),
      __map((_r) => {
        return _r as StrictHttpResponse<Error2>;
      })
    );
  }
  /**
   * @param id undefined
   * @return Found data
   */
  getMockErrorId(id: string): Observable<Error2> {
    return this.getMockErrorIdResponse(id).pipe(
      __map(_r => _r.body as Error2)
    );
  }
```
Now, I would like to pass custom headers into this API call. Would it be possible to add this as an optional parameter?

My app consists of several _wigets_ and I want to log api calls for every widget. Since swagger generated api module is a _black box_ which can be regenerated I cannot modify it's code. I would like to use HttpIterceptor to log every API call but for that I need to add header with widget hash to identify each call.

**Comment by luisfpg** [comment]
I would suggest that you copy the templates dir and modify both `operationResponse.mustache` and `operationBody.mustache` to add this custom parameter.

**Comment by GeorgeKnap** [comment]
@luisfpg 
Well, that would be an option, but modifying local copy of npm library looks to me equally terrible solution as modifying generated code.

**Comment by luisfpg** [comment]
Actually you don't have to modify the local library.
Create a folder, say, `api-templates` in your project, and copy all files in the library templates to that.
Then set the `templates` option in `ng-swagger-gen.json` to reference your new folder.

**Comment by GeorgeKnap** [comment]
That sounds like the way to go. Thanks
