### ISSUE TITLE
Reference from another file don't work

### ISSUE THREAD

**Issue by bastienmoulia** [cyclosproject/ng-swagger-gen#156]
Hi,

I have multiples API with different yaml files for each API. I would like to use the [Remote Reference Syntax](https://swagger.io/docs/specification/using-ref/#syntax) to have a single yaml for all models.

Actually i reference it with something like 
```yaml
schema:
   $ref: "./model.yaml#/definitions/Stock"
```
But at the generation I have no model Stock generated and a service with Schema instead of my model
```js
getStock(nodeRefLinkEncoded: string): Observable<Schema> {
```

I can work on a PR, but don't know how to start.

**Comment by speedfl** [comment]
+1

**Comment by battika** [comment]
Hello, is there a chance for supporting remote references? It would be very helpful when it comes to using common models in multiple swagger files.

**Comment by luisfpg** [comment]
ng-swagger-gen is currently depending solely on community PR's to evolve.
We (the original authors) have switched from Swagger 2 to OpenAPI 3 long ago, and have developed https://github.com/cyclosproject/ng-openapi-gen as the successor of ng-swagger-gen.
So, either someone will step up and implement it, or it will never be implemented.

**Comment by battika** [comment]
Thanks for the insight. I guess this can be closed then.

**Comment by luisfpg** [comment]
See #254
