### ISSUE TITLE
__BaseService undefined

### ISSUE THREAD

**Issue by remkoboschker** [cyclosproject/ng-swagger-gen#161]
We're having issues with __BaseService being undefind when building an application in production mode.
We're on Angular 7.2.2 and ng-swagger-gen 1.4.3 and  "@angular-devkit/build-angular": "~0.11.4".
The code is generated correctly, but the buil fails on ``class XyzService extends __BaseService``. ``__BaseService undefined`` The file ``../base-service.ts`` exists and the generated import statement is ``import { BaseService as __BaseService } from '../base-service';``. Do any of you have the same issue? It appears that the compiler has an issue with the leading underscores, but I can not understand why.

**Comment by remkoboschker** [comment]
Could it be that the base-service is undefined, because the configuration is not injected properly somehow?

**Comment by luisfpg** [comment]
I can't reproduce.
I've attached a minimal example from scratch, and it compiles and runs well: 
[empty.zip](https://github.com/cyclosproject/ng-swagger-gen/files/2836055/empty.zip)

Can you, please, dig a bit deeper to find out what is causing the problem?

**Comment by remkoboschker** [comment]
To be more precise. The build works. But when running the app in the browser we get the __BaseService undefined error. Updating @angular-devkit/build-angular to 0.13.0 seems to solve the issue. So I guess it is not specific to ng-swagger-gen. I do not see anything in the release notes of the builder that explains.

**Comment by remkoboschker** [comment]
It was this issue https://github.com/angular/angular-cli/issues/13212
