### ISSUE TITLE
UTF8-BOM json parsing

### ISSUE THREAD

**Issue by bhillbun** [cyclosproject/ng-swagger-gen#17]
I'm generating some swagger.json using the .NET core Swagger Swashbuckle library and it appears to be putting a BOM at the beginning of the json response.  Most client's, from what I've read, know how to handle this, but it appears this is not happening when I try to generate using the given directions.  When I copy the petstore json directly into the same file, same results occur.  If I save the petstore json directly to a new file it works.  Any chance this could be updated to handle the UTF8-BOM?

**Comment by luisfpg** [comment]
Can you, please, try the following change and see if it works?

- Checkout the project somewhere from the master branch
- Change the ng-swagger-gen.js file, before line 76 (before the `JSON.parse` call), adding the following line: `swaggerContent = swaggerContent.replace(/^\uFEFF/, '');`
- Run `npm install`
- Then `npm link`

This should link the local version as a global module, and the ng-swagger-gen command should use the modified version. Report back if it fixes your issue.

**Comment by bhillbun** [comment]
Sorry about the late response.  This worked perfectly.

**Comment by luisfpg** [comment]
I'm reopening it so it can be closed with the proper commit.
