### ISSUE TITLE
OpenApi v3

### ISSUE THREAD

**Issue by aersamkull** [cyclosproject/ng-swagger-gen#171]
Would you be open to some contribution to at least partially support OpenApi v3? I think it should be supported while keepting support for v2. The background is that our generater, https://github.com/domaindrivendev/Swashbuckle.AspNetCore, is making the transition to OpenApi v3

**Comment by luisfpg** [comment]
See https://github.com/cyclosproject/ng-openapi-gen
It is another project, not meant to generate code 100% compatible with ng-swagger-gen, but the changes are minor.
