### ISSUE TITLE
How to change the output depending on a condition?

### ISSUE THREAD

**Issue by mbtakanov** [cyclosproject/ng-swagger-gen#174]
So, first of all, I can't change the input (.json file), because it is auto generated. Based on that, I have a requirement where I need to output different version of the code of the service. Here is what I need:

If the method is GET, create this 
```
const someVar = {
    method: 'GET',
    url: 'some-url',
    params: params
};
(using the variable later on)
```

If the method is POST, create this 
```
const someVar = {
    method: 'POST',
    url: 'some-url',
    data: params
};
(using the variable later on)
```
I found that the mustache syntax doesn't provide `if` statements with a condition. The only `if` statement they provide is if the condition is `true` or `false`. Based on that I can easily implement what I need, but unfortunately, like I said, I can't change the input.

So based on all that information, is it possible to create what I need?

**Comment by luisfpg** [comment]
Well, that is one of the limitations of Mustache.
Can't you just always generate with the 2 fields?:
```typescript
const someVar = {
    method: '{{operationMethod}}',
    url: 'some-url',
    params: params,
    data: params
};
(using the variable later on)
```
Otherwise I can't think of an easier way than touching the `ng-swagger-gen.js` to add more context to the templates.

**Comment by mbtakanov** [comment]
Hey, I manage to fulfill the requirement by inspecting the `service` object ( `ng-swagger-gen.js`:170) which is describing the json file (which was auto generated by swagger) and it appears that there was a number of helpful properties like `paramIsQuery`, `paramIsBody`, etc., so based on that I manage to inject a custom code in `ng-swagger-gen.js` between line 170 and like 171 (just before the code is generated for the template for a service) where I look for at least one query param and then create a property `hasQueryParams` which I use in mustache templates in order to create `param` variable or if there is at least one body param, I create `hasBodyParams` and use this flag to create `data` property. Based on that, I loop through the array of params and fill the two variables in the mustache template.
