### ISSUE TITLE
Shared requests

### ISSUE THREAD

**Issue by bacmanni** [cyclosproject/ng-swagger-gen#175]
Is there some automatic way to share requests when using ng-swagger-gen? I mean if I have multiple same components on the page and they are calling exactly same url. I have been using .pipe(share()) before.

If this is not possible, what is the best way to do it with ng-swagger-gen? Using angular interceptor?

**Comment by luisfpg** [comment]
The `Observable`s returned by generated methods are cold. You can just `pipe` them with the `share()` operator, or any other operator you like.
