### ISSUE TITLE
camelCase for models

### ISSUE THREAD

**Issue by yanjun-liu** [cyclosproject/ng-swagger-gen#176]
Hi, nice project, thanks a lot :). I see you are beginning to support camelCase for services. It would be very nice that if we could have models with camelCase also. It is a bit inconsistent in the code now about casing.

**Comment by luisfpg** [comment]
The idea was to fix cases where the API specification is "inconsistent", declaring operations with pascal case.
Your idea is to fix cases where models are camel case, to force them to be picked case?

**Comment by yanjun-liu** [comment]
Thank you for your reply. Yes, I mean if we could use picked case for property name of models, for example, I have a generated model: 

instead of:

export interface ContactInfo {
  Name?: string;
  Phone?: string;
  EMail?: string;
}

could we get the following?:

export interface ContactInfo {
  name?: string;
  phone?: string;
  eMail?: string;
}

In our project, we use camel case for class, interface members. It would be better if we could keep it consistent everywhere

**Comment by luisfpg** [comment]
Sorry, that in not possible.
The interfaces reflect the object received / sent.
Changing the property names would require a preprocessing of the object graph after a response and before a request, and that is something we won't do.
