### ISSUE TITLE
YAML anchors does not work

### ISSUE THREAD

**Issue by miliardopiscrat** [cyclosproject/ng-swagger-gen#177]
When using anchors in swagger YAML file according to: https://swagger.io/docs/specification/2-0/enums
Generated parameter look like:

filterBy?: '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]';

filterBy is a string parameter in query.

This problem does not exists when generating from json file.

**Comment by luisfpg** [comment]
See #254
