### ISSUE TITLE
What does this project offer that the official Swagger Codegen does not?

### ISSUE THREAD

**Issue by VictorioBerra** [cyclosproject/ng-swagger-gen#180]
I imagine other people got here by googling "Angular Swagger Code Generator" and saw this:

![image](https://user-images.githubusercontent.com/2934507/58265015-7ecb1f80-7d44-11e9-930c-406284bc8417.png)

https://swagger.io/tools/swagger-codegen/

This makes me wonder, if this project just a more featurefull take on the official one?

**Comment by luisfpg** [comment]
The official swagger codegen is written in Java.
This one runs on node.js, which makes it easier to integrate with other node projects.
