### ISSUE TITLE
Remove from generated services an unused header line

### ISSUE THREAD

**Issue by danielessedi** [cyclosproject/ng-swagger-gen#190]
On  generated services appends "Content-Type" to __headers , but this is not setted to __headers again.
This issue can be resolve like this other: 
https://stackoverflow.com/questions/47805542/angular-httpclient-append-headers-to-httpheaders

**Comment by luisfpg** [comment]
Actually, after reviewing, that line just stayed there, but should've been removed.
If we manually append content type when posting form data, we break the request, as the browser won't append the boundary.
I'll just remove this line.
