### ISSUE TITLE
Add basic authentication option

### ISSUE THREAD

**Issue by johnthagen** [cyclosproject/ng-swagger-gen#191]
Our web backend requires authentication to access its schema. Currently, `ng-swagger-gen` does not allow a user to pass a username/password through its CLI so that it can use that to authenticate to the server and retrieve the schema.

A similar question for a related tool: https://stackoverflow.com/questions/42119616/using-swagger-codegen-with-username-and-password-basic-auth

**Comment by papirosko** [comment]
basic authentication works like this:

`  "input": "https://username:passwprd@server.com/path/to/swagger.json",
`

**Comment by johnthagen** [comment]
@papirosko That works, thanks. I would suggest a small blurb in the README showing users how to do this.
