### ISSUE TITLE
[Feature Request] add optional querystring param to service

### ISSUE THREAD

**Issue by Diluka** [cyclosproject/ng-swagger-gen#204]
### add optional querystring param to service

`HttpParams` can accept optional param querystring to build requests
https://github.com/angular/angular/blob/5ae9b76a9b8618ebe0e734532c576e6d38ba72cd/packages/common/http/src/params.ts#L104-L116

some params are prebuilt by query builder. needs to pass querystring to `HttpParams`

**Comment by luisfpg** [comment]
There's no plans to keep adding new functionality to ng-swagger-gen, unless if it is contributed externally.
I'd actually handle that by modifying the templates.
