### ISSUE TITLE
Different sort order of generated properties

### ISSUE THREAD

**Issue by ma-ed** [cyclosproject/ng-swagger-gen#209]
Whenever I generate the API from a swagger file that a colleague of mine already generated I get changes on almost all model interfaces. That is because, although the swagger file is identical, the generated properties are not in the same order as the generated properties of other teammembers.

For example this is what the generated file looks like on my machine:
```TypeScript
/* tslint:disable */
import { AgentType } from './agent-type';
export interface AgentData {
  id?: string;
  homepage?: string;
  type?: AgentType;
  taxNumber?: string;
  socialInsuranceNumber?: string;
  taxAuthorityNumber?: string;
  vatNumber?: string;
  courtageInsurance?: string;
  courtagePensionFund?: string;
  courtageProvisionFund?: string;
  comment?: string;
  paymentPerEmployee?: boolean;
}
```
and this is how it is generated from an other machine:
```TypeScript
/* tslint:disable */
import { AgentType } from './agent-type';
export interface AgentData {
  vatNumber?: string;
  id?: string;
  type?: AgentType;
  taxNumber?: string;
  socialInsuranceNumber?: string;
  taxAuthorityNumber?: string;
  homepage?: string;
  courtageInsurance?: string;
  courtagePensionFund?: string;
  courtageProvisionFund?: string;
  comment?: string;
  paymentPerEmployee?: boolean;
}
```
You can see that the ```vatNumber``` and the ```homepage``` got moved to another line.

We use version 1.8.1 with the following config
```JSON
{
    "$schema": "../../../node_modules/ng-swagger-gen/ng-swagger-gen-schema.json",
    "swagger": "http://localhost:8070/swagger/api/v1/agents",
    "output": "src/app/agent/api",
    "ignoreUnusedModels": true,
    "minParamsForContainer": 2,
    "defaultTag": "api",
    "removeStaleFiles": true,
    "modelIndex": true,
    "serviceIndex": true,
    "apiModule": true,
    "enumModule": true,
    "generateExamples": false
  }
```

Is there anything that influences the sort order of the generator?

**Comment by luisfpg** [comment]
in https://github.com/cyclosproject/ng-swagger-gen/blob/702505b4df18a139e76577499a0416ac2254c062/ng-swagger-gen.js#L681 properties are sorted by model name, so that parent properties, for example, are all together. We could also add a second level sort by property name, so this problem would be fixed.
Can you send a PR?
