### ISSUE TITLE
rxjs 5.5 dependency

### ISSUE THREAD

**Issue by josh-sachs** [cyclosproject/ng-swagger-gen#21]
Looks like the templates in this package assume rxjs 5.5 which is a higher version than what is required by angular 4.3. Not sure what the downsides are, but it might be worth considering including dependencies in the package.json

> angular/common: ">=4.3.0",
> angular/core: ">=4.3.0",
> "rxjs": ">= 5.5.0",
> "zone.js": ">= 0.8.4"

**Comment by luisfpg** [comment]
Thanks for noticing this, @josh-sachs 
Yes, the generated code uses lettable operators for observables. And that started being the "de facto standard" in angular 5.
The point is that the generator itself doesn't depend on angular, and if someone uses customized templates, could even be made a generic generator for typescript, without even depending on angular. In this sense, adding the angular, or even rxjs dependencies would be "wrong".
On the other hand, the generated code does depend on such libraries.

Maybe if we just add dependencies to `"@angular/core": ">=4.3.0"` and `"rxjs": ">= 5.5.0"`, that would be enough?

**Comment by luisfpg** [comment]
Instead of adding the dependency to the generator, I've actually added a Requirements section to README.md, so it is clear that rxjs 5.5.0 or higher is required for the generated code.
