### ISSUE TITLE
specify "Accept" header for request

### ISSUE THREAD

**Issue by vanca** [cyclosproject/ng-swagger-gen#212]
I have a GET request that returns an "application-octet stream". On the backend side I'm using .net core 3.0 with swashbuckle and I've configured the controller to produce responses with the 'application/octet-stream' mime type and regenerated my services using ng-swagger-gen. But the request "Accept" header is still "application/json". What can I do to make it accept "application/octet-stream" responses?
![image](https://user-images.githubusercontent.com/13727222/69832030-c622f300-1234-11ea-9ef0-0c4e79cd8ebc.png)

**Comment by luisfpg** [comment]
Actually, the accept is a list of json, plain and */*, so it accepts anything.
