### ISSUE TITLE
[Feat] Add an argument in the CLI to select the log level

### ISSUE THREAD

**Issue by bastienmoulia** [cyclosproject/ng-swagger-gen#215]
Hi,

I use a lot of `ng-swagger-gen` command and I would like to not display some logs (`console.info`).

I think we can use [Winston ](https://github.com/winstonjs/winston) or another logger for that.

An exemple of use can be:
`ng-swagger-gen --config custom-config.json --log-level error`

**Comment by luisfpg** [comment]
See #254
