### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by M-Patrone** [cyclosproject/ng-swagger-gen#217]
I don't really know, when this error happens, but I think the solution is to pass a paramter to extend the timeout of the request. Here are the details of the error: 

Error reading swagger location http://localhost:55389/swagger/v1/swagger.json: Error: Error downloading http://localhost:55389/swagger/v1/swagger.json socket hang up

**Comment by veslav3** [comment]
@M-Patrone I think I have the same issue with Gitlab CI. (not local builds)

**Comment by M-Patrone** [comment]
@veslav3 Try it with my fork (https://github.com/M-Patrone/ng-swagger-gen) and let me know if it helped.

**Comment by oslTrifork** [comment]
Is there any reason why this couldn't be a parameter like M-Patrone proposed through his fork? The time is takes to generate our json file is often longer than 20 sec, up to a minute actually. It would be useful to be able to control this parameter ourselves.

**Comment by luisfpg** [comment]
@oslTrifork Mmmm... actually I didn't consider the case that the descriptor is generated on-the-fly.
I'm used to call the generation before every start and build, and this would make it impossible.
Anyhow, the point is that there were some things to fix in this PR, and I decided to keep it as simple as possible, for the sake of having minimal time to work on this project.
Please, open a new issue requesting the parameter to be added.
