### ISSUE TITLE
duplicate operation ids with different verbs

### ISSUE THREAD

**Issue by josh-sachs** [cyclosproject/ng-swagger-gen#22]
Swagger sometimes produces duplicate operation ids, for example when a GET operation has a corresponding HEAD operation. 

SwaggerUI indexes these operations... can ng-swagger gen do something similar, or provide a way to exclude specific verbs?

```
[GET] GetUserList(...)
[HEAD] GetUserList_1(...)
```
or 
```
[GET] GetUserList(...)
[HEAD] GetUserList_Head(...)
```

**Comment by luisfpg** [comment]
Yes, we could append a suffix for duplicated operation ids.
I think the approach taken by SwaggerUI should be ok: when processing an operation, and its id is already in use, keep incrementing a counter as suffix.
As any operations could potentially have the same id, even with the same HTTP method, appending the HTTP method could not be enough.
