### ISSUE TITLE
There are many generic types in the models of swagger, and how can I exclude them from the ng-swagger-gen?

### ISSUE THREAD

**Issue by Frodez** [cyclosproject/ng-swagger-gen#221]
My backend project includes models with parameterized type. And I use the springfox, a opensource plugin for intergratation between swagger and spring, to transfrom my end points and models to swagger apis and schemes.

But the schemes have many generic types because of the reason above. And then when I use the ng-swagger-gen to generage code, they are included. However, I can use the models with base type to form the app.

How can I exclude them from the ng-swagger-gen?

**Comment by luisfpg** [comment]
Sorry, there's no way to do it.
Generic types are not defined in the swagger spec.
