### ISSUE TITLE
Webflux Flux and Mono Return Types

### ISSUE THREAD

**Issue by datumgeek** [cyclosproject/ng-swagger-gen#224]
Is there a recomendation for using ng-swagger-gen with Spring Webflux Mono and Flux return types?

here's an example REST Get Method in Spring Webflux (using Reactive Mongo repository)

```
    @GetMapping(value = "/api/runs")
    public Flux<Run> getRuns() {
        return runRepository.findAll();
    }
```

These are the types that get generated

```
export interface FluxRun {
  prefetch?: number;
}
```

and

```
export interface Run {
  itemIds?: Array<string>;
  requestUrls?: Array<string>;
  resultsUrls?: Array<string>;
  runId?: string;
  runStart?: number;
  runStop?: number;
  targetUrl?: string;
}
```

The generated controller's method returns the FluxRun type

```
  getRunsUsingGET(): __Observable<FluxRun> {
    return this.getRunsUsingGETResponse().pipe(
      __map(_r => _r.body as FluxRun)
    );
  }
```

**Comment by luisfpg** [comment]
No, ng-swagger-gen is a generator for client-side Angular.
Flux / Mono are server-side concepts in Spring.
You just can't model a Flux as a Swagger model.

**Comment by datumgeek** [comment]
i'd like to consume those services from client side angular...  is that not possible?

**Comment by luisfpg** [comment]
Sure it is. But not modeled as Flux / Mono, but as Array / Object.
What is documented in Swagger is just the JSON format for data exchange.
Flux / Mono concepts only exists in the server-side.

**Comment by luisfpg** [comment]
By the way, if you're starting with it, I'd recommend using https://github.com/cyclosproject/ng-openapi-gen instead.

**Comment by datumgeek** [comment]
ok, so just for completeness...

i updated the non-blocking rest responses to block so they can return types that swagger likes...

here's an example:

```
    @GetMapping(value = "/api/runs")
    public List<Run> getRuns() {
        return runRepository.findAll().collectList().block();
    }
```

the corresponding generate typescript code looks like this

```
  getRunsUsingGET(): __Observable<Array<Run>> {
    return this.getRunsUsingGETResponse().pipe(
      __map(_r => _r.body as Array<Run>)
    );
  }
```
