### ISSUE TITLE
Angular 9 with IVY and AOT

### ISSUE THREAD

**Issue by richardsengers** [cyclosproject/ng-swagger-gen#225]
Is this library suppose to work with Angular 9 and ivy with aot?
I keep getting errors when ivy enabled with aot

node_modules/{project}/dist/api.module.d.ts:6:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

The generated ApiModule looks like this:

```
import { ModuleWithProviders } from '@angular/core';
import { ApiConfigurationInterface } from './api-configuration';
/**
 * Provider for all Api services, plus ApiConfiguration
 */
export declare class ApiModule {
    static forRoot(customParams: ApiConfigurationInterface): ModuleWithProviders<ApiModule>;
}

```

Am I doin gsomething wrong or is this library not yet Ivy ready?

**Comment by luisfpg** [comment]
The library hasn't been tested with Angular 9.
I don't have much time to work on ng-swagger-gen nowadays, but I expect to find some time in the next couple of weeks.

**Comment by luisfpg** [comment]
Actually, I've tested a simple project with Angular 9 / Ivy and it works out of the box.
Can you provide an example project?

**Comment by GeorgeKnap** [comment]
@richardsengers I believe I had the same error. To fix it I had to run ngcc, or put a postinstall script into package.json:
`"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`

**Comment by luisfpg** [comment]
I'll close this one for now.
Any issues with Ivy, please, comment again.

**Comment by richardsengers** [comment]
Thanks for the feedback. Maybe it's because I've upgraded from angular 8.
On a new Angular 9 project I don't have the issue

@GeorgeKnap unfortunately ... i've already tried it, but without any luck.

I'm going to start a new Angular 9 project and copy paste my components.
