### ISSUE TITLE
Add timeout parameter for on-the-fly code generations

### ISSUE THREAD

**Issue by oslTrifork** [cyclosproject/ng-swagger-gen#230]
Hi

Requested from #217, it would be greatly appreciated if we could have a parameter for setting timeout when downloading swagger.json from remote

In our case, the average time it takes to download one of our swagger schematics  is 1 min, so currently we can't use this project, since the timeout is 20 seconds.

We appreciate the hard work being put into this.

**Comment by jrel** [comment]
I will try fix this
