### ISSUE TITLE
Option to not run the proxy setup

### ISSUE THREAD

**Issue by bokuwagaijin** [cyclosproject/ng-swagger-gen#237]
Currently we have our proxy setup in our npm config in order to actually be able to install packages but because we generate from our API's running over localhost the swagger gen automatically running through the proxy means that it never resolves and we always get a 503 error.
When we remove that line or add a flag to optionally ignore it the swagger gen works as it did prior to version 1.8.0.
Am I able to submit a PR to add a flag to disable the proxy for those scenarios where we are generating from our own APIs locally please?

**Comment by luisfpg** [comment]
Sure, the PR would be welcome

**Comment by bokuwagaijin** [comment]
Thanks. Let me know if any improvements can be made. I tested this in my clients environment and it works as I want.
