### ISSUE TITLE
Why ignore in source control the generated code?

### ISSUE THREAD

**Issue by simeyla** [cyclosproject/ng-swagger-gen#24]
Very confused about this statement:

output_dir is the directory where the generated code will be outputted. It is recommended that this directory is ignored on GIT (or whatever source control software you are using)

But this is generated runtime code? Why would it not be in source control? I don't see any kind of automated generation at build time - is this the intent?

**Comment by luisfpg** [comment]
It is a general consensus that only source artifacts (source code, descriptors, etc) are committed to the source control system, not generated artifacts. For a good explanation, see https://perlmaven.com/dont-keep-generated-files-in-version-control.
You can make sure your generated classes are always consistent with the swagger descriptor (which itself can be in the source control, as it is a source artifact) by following this section: https://github.com/cyclosproject/ng-swagger-gen#setting-up-a-node-script.
So, if you incorporate to always run those scripts through `npm`, not `ng serve` directly, the generated files will always be consistent.
