### ISSUE TITLE
Error: Invalid swagger specification. Must be a 2.0. Currently undefined

### ISSUE THREAD

**Issue by SharmaHarsh7** [cyclosproject/ng-swagger-gen#242]
When I run this command:
`node_modules\\.bin\\ng-swagger-gen -i http://localhost:50001/swagger/v1/swagger.json -o src/app/api/`

It gives me below error:

Invalid swagger specification. Must be a 2.0. Currently undefined

**Comment by samsonkumawong** [comment]
What did you do to resolve this issue?

**Comment by samsonkumawong** [comment]
I solved it by adding 
"swagger": "2.0" 
in the json file

**Comment by samheihey** [comment]
I was using swashbuckle for my backend service which defines the api json file to open api v3 by default, to resolve this and for ng-swagger-gen to run smoothly, I need to add the 
`app.UseSwagger(c =>
     c.SerializeAsV2 = true
);`
for backward compatibility of the specification from open api v3 to swagger v2

Or, simply add 
`"swagger": "v2"` to the existing json file for ng-swagger-gen to generate the code
