### ISSUE TITLE
Use pipe(take(1)) or pipe(first()) for all methods since http will never give a second result

### ISSUE THREAD

**Issue by gideruette** [cyclosproject/ng-swagger-gen#249]
I suggest that we can add a take(1) or the operator first() to methods pipes so that we don't need to unsubscribe observable. Http won't give us a second value after return

**Comment by andresbm05** [comment]
That is not needed. Http request Observables returned by HttpClient are self-completed after emitting the response, so you dont need to unsubscribe and it will not cause memory leaks.
