### ISSUE TITLE
add custom variables to be substitued in templates

### ISSUE THREAD

**Issue by kieranjohn** [cyclosproject/ng-swagger-gen#253]
Hi 

First off .. love this project ❤ 

I have a feature request.

Would you be able to add custom variables to be replaced in some of the templates? 

Ideally, supply them as arguments in the configuration file as a JSON object

```json
{
  "$schema": "./node_modules/ng-swagger-gen/ng-swagger-gen-schema.json",
  "customVars": {
    "replaceMe":"with some custom string"
  }
}
```

Thanks

**Comment by luisfpg** [comment]
See #254
