### ISSUE TITLE
Errors after upgrade to latest version

### ISSUE THREAD

**Issue by developerTN** [cyclosproject/ng-swagger-gen#257]
Hello community,

I have upgrated the ng-swagger-gen lib to the latest version (it was 1.7.0) and now I have a lot of errors mainly this error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
as far I saw the paths now are generating using  encodeURIComponent
how can I disable this ? it looks to me a breaking a change especially that I have more than 100 services that is throwing this error

**Comment by developerTN** [comment]
@luisfpg

**Comment by luisfpg** [comment]
Can you show an example of both the descriptor and the generated file?
The latest version is 2.3.0, there might be breaking changes in relation to 1.7.0.

**Comment by developerTN** [comment]
here a screenshot
![image](https://user-images.githubusercontent.com/8679643/109300804-4d478800-7837-11eb-8416-69b1f5289adb.png)

**Comment by developerTN** [comment]
here is a screenshot
![image](https://user-images.githubusercontent.com/8679643/109300860-66e8cf80-7837-11eb-914e-7ec2ab1fedb3.png)

**Comment by developerTN** [comment]
@luisfpg it's should be due to the encodeURIComponent that wasn't present before in URLs

**Comment by luisfpg** [comment]
Fix released in version 2.3.1

**Comment by developerTN** [comment]
@luisfpg thanks a lot :) how can I download this version ? is it already available with npm install ?

**Comment by luisfpg** [comment]
It is already available in npm.

**Comment by developerTN** [comment]
thanks a lot, problem solved !
