### ISSUE TITLE
remove HttpClientModule from ApiModule imports/exports.

### ISSUE THREAD

**Issue by josh-sachs** [cyclosproject/ng-swagger-gen#28]
When HttpClientModule is imported by the ApiModule, HTTP_INTERCEPTORS collection gets overridden. 

I believe the best practice would be to make importing HttpClientModule a requisite of the root module imports...

```
// root module
...
import: [
     HttpClientModule,
     ApiModule,
     ...
],
providers: [
     { provide: HTTP_INTERCEPTORS, multi: true, useClass: SomeInterceptor }
]
```

Some alternatives, 
- make the import/export of HttpClientModule an ng-swagger-gen configuration setting.
- generate an exported array of services that can be used in lieu of ApiModule:

```
// services/index.ts
export const API_SERVICES = [
// generated service collection
...
];

// index.ts
export { API_SERVICES } from "./services/index.ts";
```

**Comment by luisfpg** [comment]
@josh-sachs  I didn't understand the problem.
We have a project that has the following:

**root AppModule**:
- imports ApiModule
- imports CoreModule
- imports SharedModule
- (no exports)

**ApiModule** (generated):
- imports and exports HttpClientModule (from angular)
- provides the generated services

**CoreModule** (provides all singletons):
- imports SharedModule
- (no exports)
- provides HTTP_INTERCEPTORS

**SharedModule** (imported here and on lazy-loaded modules):
- imports and exports CommonModule (from angular)
- imports and exports RouterModule (from angular)
- also imports and exports angular material modules

And the interceptors provided by CoreModule are correctly used in requests.
Can you, please, detail the problem?

**Comment by josh-sachs** [comment]
I actually think the issue was how I was web-packing the Api module for use in my angular project, the angular namespace was not properly configured in the externals list.  This was resulting in an HttpClient type scoped to the ApiModule and a different class with the same name scoped to the main project. 

Apologies, this issue can be closed.

**Comment by JoostvdB94** [comment]
I have this same issue. 
@josh-sachs What was the change in the webpack settings that fixed this behaviour?

**Comment by GeorgeKnap** [comment]
This is a real issue, HttpClientModule should be imported only once  (see [angular github issue](https://github.com/angular/angular/issues/20575) ).   In my project we have multiple microservices, each one used to generate api module via this library. Thus we have several modules each importing HttpClientModule. That is not correct. However there is a quick solution, use local version of mustache files and remove it from module.mustache .

**Comment by Lonli-Lokli** [comment]
@josh-sachs can you please reopen this issue? It's really an issue with lazy modules
