### ISSUE TITLE
petstore example does not work

### ISSUE THREAD

**Issue by sinofool** [cyclosproject/ng-swagger-gen#29]
It seems ts strict compile failed on generated code.
4 lines petstore example at the bottom of readme document does not compile.
Please document or fix.

**Comment by sinofool** [comment]
Related:
https://github.com/swagger-api/swagger-codegen/issues/7231

**Comment by luisfpg** [comment]
@sinofool Can you, please, upgrade rxjs to at least 5.5 and test?
If this is the case, please check out the requirements section: https://github.com/cyclosproject/ng-swagger-gen#requirements

**Comment by sinofool** [comment]
I found the problem is the project was created with angular-cli@1.4.5. All the libraries in package-lock.json are updated and matching the requirements but still not working.

https://github.com/angular/angular-cli#updating-angular-cli
This document mentioned **"rm -rf node_modules && npm install"** fixed my problem. 

It looks like an angular-cli upgrade best practice. Only update cli and dependencies version does not work, even with the same "ng version" output does not help.

Sorry for the distraction and thank you @luisfpg .
