### ISSUE TITLE
Can this be configured to work with JWT?

### ISSUE THREAD

**Issue by Garrick36** [cyclosproject/ng-swagger-gen#30]
If my angular project uses JWT and AuthHttp instead of the generic HttpClient, can this plugin be configured to use that in the generated services?

**Comment by luisfpg** [comment]
You would need to customize the templates.
You can copy all mustache files in `ng-swagger-gen`'s `templates` folder to some folder in your project and set the `templates` field to point to that in `ng-swagger-gen.json`.
The file you need to change is `operationResponse.mustache`.
It contains the logic to instantiate the `HttpClient`.

**Comment by Garrick36** [comment]
Great. Thank you for the quick response
