### ISSUE TITLE
Adding HTTP Header for Bearer token

### ISSUE THREAD

**Issue by kaneda-fr** [cyclosproject/ng-swagger-gen#32]
Hi,

I need bearer token authentication for my API.
It would be great if we can adds an authentication token in the client http header.

Any advice on how to best implement this ?

Thanks

**Comment by luisfpg** [comment]
You have to implement an interceptor, as documented here: https://angular.io/guide/http#intercepting-all-requests-or-responses
Then just add the header, as described here: https://angular.io/guide/http#setting-new-headers

**Comment by kaneda-fr** [comment]
Works great, thanks !
