### ISSUE TITLE
Best way to specify custom url for API

### ISSUE THREAD

**Issue by silentFred** [cyclosproject/ng-swagger-gen#35]
Firstly, awesome contribution. This is by far the best Angular swagger gen approach I have seen so far. 

One quick question though: What is the best way to provide a different endpoint for the API instead of the endpoint provided for code gen.

Cheers,

**Comment by luisfpg** [comment]
It was missing in the main README, and was only present in the wiki, so now I've added this section to the README, which should explain it in details: https://github.com/cyclosproject/ng-swagger-gen#specifying-the-root-url--web-service-endpoint
