### ISSUE TITLE
ResponseEntity<?> always generates null body.

### ISSUE THREAD

**Issue by gwellner** [cyclosproject/ng-swagger-gen#39]
Hi,
I really love your code generation plugin, i have a weird question.

I know that code like this almost shouldn't exist but still we have a Rest Service which has 

```java

    @RequestMapping(value = "{param1}/{param2}", method = GET)
    public ResponseEntity<?> getConfigInfo(@CookieValue(value = "uid", defaultValue = "") String uid ) {
}

```

and this generates

```javascript
    return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: {} = null;

        return _resp.clone({body: _body}) as HttpResponse<{}>;
      })
    );
```

where body will always be updated with null.

Is this a wanted behavior or ist it possible that _body will be set to _resp.body in this case ? or just clone without updating body with null.

**Comment by luisfpg** [comment]
There seems to have 2 issues: Cookie parameters are currently not supported and there seems to have no declared response type for the path in your swagger definition, just like #39

**Comment by ankush2304** [comment]
Hi,

I found below issue in package - 
I am always getting null response because of the above generated code, where in clone method we replacing response body with null.
      return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: {} = null;

        return _resp.clone({body: _body}) as HttpResponse<{}>;
      })
    );
Regards,
Ankush

**Comment by ankush2304** [comment]
Hi,

Can you fix the below issue - 
Our response doesnot have any model it just java Response object with json embedded in it
 let _body: void = null;
 return _resp.clone({body: _body}) as HttpResponse<void>;

Regards,
Ankush

**Comment by ankush2304** [comment]
Hi,

Can you please help in how configure multiple in app.module.ts in case of multiple swagger.

Regards,
Ankush

**Comment by luisfpg** [comment]
As said in #38, use multiple configuration files. Each one will have a separated output folder.
Then just import the corresponding modules for each configuration in your app.module.ts.
