### ISSUE TITLE
Add support for inline enums (defined within a model)

### ISSUE THREAD

**Issue by vladimirpetrenko** [cyclosproject/ng-swagger-gen#41]
[FEATURE REQUEST] Please add support to generate TypeScript enums

Example:

SWAGGER-FILE:

 "TestDto": {
      "type": "object",
      "properties": {
        "stateEnum": {
        "type": "string",
        "enum": [
           "NEW",
           "OLD"
        ]
      }
 }

OUTPUT-FILEs:

file:// test-dto.ts
export interface ParameterDto {
  stateEnum?: StateEnum;
}

file:// state-enum.ts
export enum StateEnum{
  NEW= "NEW",
  OLD= "OLD"
}

TypeScript => Enums: https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by luisfpg** [comment]
TypeScript started supporting string enums in 2.4. In fact, I didn't even had catch up on that...
It is not clear to me which is the advantage over the current approach, of generating the enum type as an union type of the possible values, plus a module to enumerate them.
So, for client code, the usage would be `StateEnum.OLD` in both cases...
And currently, it is possible to use `StateEnum.values()` to get a list of all available values.
The only thing that can be argued is to reduce the generated code size a bit, but I don't have a clear idea on the impact.

**Comment by vladimirpetrenko** [comment]
Please can you point me to an example or description of your approach? I did not find any solution for the enum problem in generated api from ng-swagger-gen.

Example: Just now, i get only following code from SWAGGER-FILE(mentioned top of page) and nothing more:

OUTPUT-FILEs:
file:// test-dto.ts
```
export interface ParameterDto {
stateEnum?: string;  // only string and nothing more
}
```

**Comment by luisfpg** [comment]
Share the swagger definition.
But here is an example:
```json
{
    "UserStatusEnum" : {
      "type" : "string",
      "enum" : [ "active", "blocked", "disabled", "pending", "removed" ]
    }
}
```
Generates this:
```typescript
 export type UserStatusEnum = 
  "active" |
  "blocked" |
  "disabled" |
  "pending" |
  "removed";

export module UserStatusEnum {
  export const ACTIVE: UserStatusEnum = "active";
  export const BLOCKED: UserStatusEnum = "blocked";
  export const DISABLED: UserStatusEnum = "disabled";
  export const PENDING: UserStatusEnum = "pending";
  export const REMOVED: UserStatusEnum = "removed";
  export function values(): UserStatusEnum[] {
    return [
      ACTIVE, 
      BLOCKED, 
      DISABLED, 
      PENDING, 
      REMOVED
    ];
  }
}
```

**Comment by vladimirpetrenko** [comment]
I use original swagger definition file (petstore example) to test generation of enums: http://petstore.swagger.io/v2/swagger.json

Code part:
```javascript
        "status": {
          "type": "string",
          "description": "Order Status",
          "enum": [
            "placed",
            "approved",
            "delivered"
          ]
        },
```

My settings file (ng-swagger-gen.json) looks like this:
```javascript
{
  "$schema": "./node_modules/ng-swagger-gen/ng-swagger-gen-schema.json",
  "swagger": "./swagger.json",
  "output": "./src/app/base/generated",
  "config": "ng-swagger-gen.json",
  "ignoreUnusedModels": true,
  "minParamsForContainer": 2,
  "defaultTag": "Api",
  "removeStaleFiles": true,
  "modelIndex": true,
  "serviceIndex": true,
  "apiModule": true
}
```
My generated TS-Code looks like:

```javascript
export interface Pet {

  id?: number;

  category?: Category;

  name: string;

  photoUrls: string[];

  tags?: Tag[];

  /**
   * pet status in the store
   */
   status?: string;
}
```
But i have nothing like enum only simple string. See status in pet class.
My expectation would be enum like your examle above, but not string.

**Comment by luisfpg** [comment]
Ah, I see.
There is support for top-level enum definitions (in its own definition), but not "inline" enum definitions (within the property of another model).
I'm changing the title of this issue and will leave it open until this is implemented.

**Comment by vladimirpetrenko** [comment]
Wait for new release. Thank you big, for your support!

**Comment by luisfpg** [comment]
I'll implement it as a simple union of possible strings, not as a separated type.
It would be far more complicated to generate a separated type.
This also aligns with inline objects, which don't have an external class, but the object is defined inline.
So, in the pestore example, the resulting Pet would be like:
```typescript
export interface Pet {
  /**
   * pet status in the store
   */
  status?: 'available' | 'pending' | 'sold';
}
```

**Comment by spyro2000** [comment]
@luisfpg This is already great, thank you. But to list all possible values (e.g. in a drop down field) this values cannot be accessed at runtime. Maybe you could just enumerate them like this?

Current:

``
export interface CalloffTypeTO {
  id?: 'S' | 'T' | 'K' | 'L';
  description?: string;
}

Suggested:

```
export interface CalloffTypeTO {
  id?: IdEnum;
}

export enum IdEnum {
    'S' , 'T' , 'K' , 'L'
}
```

**Comment by pwen090** [comment]
Is there any plan to solve this like @spyro2000 mentions? Or what is the recommended clean way to get the values at runtime for a drop down list etc?

**Comment by luisfpg** [comment]
There's no plan to implement it, unless someone comes with a patch ;)
@spyro2000  mentioned a simple example, but if we're going to generate inline enums as a separated enum, then we'd also need to generate inline objects with a separated exported interface, and this could be any level deep.
Imagine this: 

```yaml
Example:
  type: object
  properties:
    enumLevel0:
    type: string
    enum:
      - A
      - B
      - C
    level1:
      type: object
      properties:
        enumLevel1:
          type: string
          enum:
            - A
            - B
            - C
        level2:
          type: object
          properties:
            enumLevel2:
              type: string
              enum:
                - A
                - B
                - C
```
It would have 3 enums to export, plus 2 interfaces, all with generated names making sure they don't clash.

That's the main reason it was never done.
