### ISSUE TITLE
File download/upload support

### ISSUE THREAD

**Issue by Ulkuurz** [cyclosproject/ng-swagger-gen#43]
Any plans to support file uploads/downloads in the future (response schema.type = 'file')?

![image](https://user-images.githubusercontent.com/10021981/37834768-cd341d74-2eae-11e8-9c8a-a20dd7c09f62.png)

**Comment by luisfpg** [comment]
We would first need to define the semantics, such as what is actually returned on the response when downloading, or expected when uploading.
For downloads, maybe a Blob (https://developer.mozilla.org/en-US/docs/Web/API/Blob) would work.
But for uploads, if the expected content type is encoded as multipart/form-data, then maybe a FormData (https://developer.mozilla.org/en-US/docs/Web/API/FormData) would have to be the expected type.
Anyway, It is currently not planned.
Help is welcome.

**Comment by luisfpg** [comment]
It will be included in the 0.11 release, with Blob's as both input and output for files.
