### ISSUE TITLE
Recommendation to manage multiples apps with multiple Apis

### ISSUE THREAD

**Issue by jogelin** [cyclosproject/ng-swagger-gen#48]
Hello,

Your library looks very interesting and I thinking how can I use it for our projects. 

We are working in a monorepo like [Nx](https://nrwl.io/nx) which can contains multiple apps. And each app can use multiple Apis (the apis are cut in microservices architecture). So for one Angular app, I have to generate models and services for multiples swagger files (one per service).

When I read your documentation I think I will have to specify one swagger file per configuration file, correct?
So I will have to put also multiple command in my package.json, one per api/swagger-file, correct ?

If yes, it is a lot of command that I will have to maintain, one per api multiply by the number of apis multiply by the number of application, correct ?

Do you think it due-able to manage multiple Apis/swagger-file in one configuration file and then generate models and services in subfolder ?

Do you think it is possible to manage multiple apps like angular-cli is already proposing ?

**Comment by luisfpg** [comment]
Supporting multiple configurations with a single file is not planned.
You can have multiple configuration files, then have a npm script that runs ng-swagger-gen for each configuration file. Suppose the following code is on `src/bin/generate.js`:
```javascript
#!/usr/bin/env node
'use strict';

var childProcess = require('child_process');

// The list of configuration files
var CONFIG_FILES = [
  'src/config/file1.json',
  'src/config/file2.json',
  'src/config/file3.json'
];

// Location of the ng-swagger-gen script
var SCRIPT = __dirname + '../../../node_modules/.bin/ng-swagger-gen';

function ngSwaggerGen(configFile, callback) {

  // keep track of whether callback has been invoked to prevent multiple invocations
  var invoked = false;

  var process = childProcess.fork(SCRIPT, ['-c', configFile]);

  // listen for errors as they may prevent the exit event from firing
  process.on('error', function (err) {
      if (invoked) return;
      invoked = true;
      callback(err);
  });

  // execute the callback once the process has finished running
  process.on('exit', function (code) {
      if (invoked) return;
      invoked = true;
      var err = code === 0 ? null : new Error('exit code ' + code);
      callback(err);
  });
}

// Run for each configuration file
CONFIG_FILES.forEach(configFile => {
  ngSwaggerGen(configFile, err => {
    if (err) throw err;
    console.log('Generation done for configuration file ' + configFile);
  });
});
```

Then, in your package.json, define a script:
```json
{
  "scripts": {
    "generate": "src/bin/generate.js",
    "start": "npm run generate && ng serve -aot",
    "build": "npm run generate && ng build -prod"
  }
}
```

Like this, for each new file you just have to adjust the `src/bin/generate.js`.
Or even better: define a convention, such as considering each json file in `src/config`.

**Comment by jogelin** [comment]
thx a lot !!!
