### ISSUE TITLE
ng-packagr support

### ISSUE THREAD

**Issue by willemsendennis** [cyclosproject/ng-swagger-gen#51]
We us ng-packagr to pack our Angular projects. However, it doesn't like the usage of exports with the same name:
`SyntaxError: Duplicate export 'NamedService'`
Where NamedService is the name of my Service.

This because of the decleration merging of the service and the module that both export the same name.

One solution could be the following, where the service and module are not exported directly but at the end like so:

```
@Injectable()
class NamedService extends BaseService {
  constructor(
    config: ApiConfiguration,
...
}
 
 
module NamedService {
 
  export interface DeleteParams {
  ...
  }
}
 
 
export { NamedService }
```

mustache:

```
import { Injectable } from '@angular/core';
import {
  HttpClient, HttpRequest, HttpResponse, 
  HttpHeaders, HttpParams } from '@angular/common/http';
import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { Observable } from 'rxjs/Observable';
import { map } from 'rxjs/operators/map';
import { filter } from 'rxjs/operators/filter';

{{#serviceDependencies}}import { {{modelName}} } from '../models/{{modelFile}}';
{{/serviceDependencies}}
{{{serviceComments}}}@Injectable()
class {{serviceClass}} extends BaseService {
  constructor(
    config: ApiConfiguration,
    http: HttpClient
  ) {
    super(config, http);
  }
{{#serviceOperations}}{{>operationResponse}}{{>operationBody}}{{/serviceOperations}}
}

module {{serviceClass}} {
{{#serviceOperations}}{{#operationParamsClass}}
{{{operationParamsClassComments}}}export interface {{operationParamsClass}} {
{{#operationParameters}}
{{{paramComments}}}{{paramVar}}{{^paramRequired}}?{{/paramRequired}}: {{{paramType}}};
{{/operationParameters}}
  }
{{/operationParamsClass}}{{/serviceOperations}}
}

export { {{serviceClass}} };
```

Is this something you would like to support?

**Comment by luisfpg** [comment]
I don't mind supporting it, as long as it doesn't break other use cases.
So, if I understand correctly, the only thing that changes is that instead of having both class and module exported, none of them should be exported on declaration and a single export in the end should export the name, which would effectively export both?
If that's the only change, I'm fine with it.
The enum models would also have the same issue, I think.
For example:
```json
{
  "models": {
    "UserStatusEnum" : {
      "type" : "string",
      "enum" : [ "active", "blocked", "disabled", "pending", "removed" ]
    }
  }
}
```
generates:
```typescript
export type UserStatusEnum =
  'active' |
  'blocked' |
  'disabled' |
  'pending' |
  'removed';
export module UserStatusEnum {
  export const ACTIVE: UserStatusEnum = 'active';
  export const BLOCKED: UserStatusEnum = 'blocked';
  export const DISABLED: UserStatusEnum = 'disabled';
  export const PENDING: UserStatusEnum = 'pending';
  export const REMOVED: UserStatusEnum = 'removed';
  export function values(): UserStatusEnum[] {
    return [
      ACTIVE,
      BLOCKED,
      DISABLED,
      PENDING,
      REMOVED
    ];
  }
}
```

**Comment by willemsendennis** [comment]
Superb!
I didn't notice the enum.
But yes, the above gives the same problem and so is the proposed solution.

**Comment by silentFred** [comment]
Completely unrelated to ng-swagger-gen...

@willemsendennis sorry to bump this but was wondering how you managed to bundle generated client code with ng-packagr? At the moment I'm trying to consume my own package - getting major complaints for the module.forRoot in my main app NgModule decorator. 

```ERROR in Error during template compile of 'DetailsApiModule'
  Function calls are not supported in decorators but 'DetailsModule' was called.
```
