### ISSUE TITLE
Not working custom header

### ISSUE THREAD

**Issue by codalprashant** [cyclosproject/ng-swagger-gen#52]
After setting up the configuration as per the document, no custom header is fired up. ALso the api is only calling option method, not any other method. Can I use this package for production ?

**Comment by luisfpg** [comment]
> After setting up the configuration as per the document, no custom header is fired up.

Do you mean this? https://github.com/cyclosproject/ng-swagger-gen#passing-request-headers--customizing-the-request

> ALso the api is only calling option method, not any other method.

The client code NEVER sends an OPTION method, but the browser does when the page and the API server are in different domains. Have you ever heard about [CORS](https://enable-cors.org/)?

> Can I use this package for production ?

We have this in production for some time already. I know of several others also.

**Comment by codalprashant** [comment]
I used the instructions https://github.com/cyclosproject/ng-swagger-gen#passing-request-headers--customizing-the-request

I know http verbs and how they works.

The custom header is not getting passed on the request.

**Comment by luisfpg** [comment]
Can you post your HttpInterceptor? And the part in your module that provides it?

**Comment by luisfpg** [comment]
Closing for now for lack of input.
If still an issue, please, reopen.
