### ISSUE TITLE
Special characters in enums results in compile errors

### ISSUE THREAD

**Issue by 7opf** [cyclosproject/ng-swagger-gen#56]
I define some string enums in swagger that contain special characters ":", "-" and spaces " " which results in compilation errors in the generated enum ts files. 
Would it be possible to have the generator replace such characters with "_" for example?

**Comment by 7opf** [comment]
Same goes for numeric enums - These could be prefixed with "_".

**Comment by luisfpg** [comment]
Yes, this needs to be fixed.
In the meantime, you can skip the enum module export, by setting `"enumModule": false` in the `ng-swagger-gen.json` file. I think the problem is with the constants exported by that module, and it should prevent this error.

**Comment by 7opf** [comment]
Yes - I fixed it by adding a string replacement and numeral check to the `toEnumName` function in pull #57
