### ISSUE TITLE
Generate example JSON from model's example section

### ISSUE THREAD

**Issue by ganqqwerty** [cyclosproject/ng-swagger-gen#58]
As far as I know, it’s  possible to specify sample output of the given call.  I would like to use this data as a mock data for my JavaScript unit tests. Is it possible for swagger-gen to include those mocks into the code it generates?

**Comment by luisfpg** [comment]
The sample output is not used on the generated services, and this is not planned.

However, as the generated services use the standard HttpClient for requests, you can mock it.
I just googled for some examples, and found pages like https://alligator.io/angular/testing-httpclient/ and https://medium.com/netscape/testing-with-the-angular-httpclient-api-648203820712
I haven't done this myself, so this is what I can suggest for now.

**Comment by ganqqwerty** [comment]
Thanks for your answer. I know how to test the services with http, but my task now is to generate mocked services for the components unit tests. 

The thing I would like swagger gen to do is to generate the mocked services alongside with the real services.
