### ISSUE TITLE
Error in generating code: Token "List" does not exist.

### ISSUE THREAD

**Issue by theashwin007** [cyclosproject/ng-swagger-gen#60]
node_modules/.bin/ng-swagger-gen -i ~/account-service-swagger.json 
Error reading swagger location /home/ashwin/account-service-swagger.json: SyntaxError: Error resolving $ref pointer "/home/ashwin/account-service-swagger.json#/definitions/List". 
Token "List" does not exist.

**Comment by theashwin007** [comment]
[account-service-swagger_json.txt](https://github.com/cyclosproject/ng-swagger-gen/files/2054771/account-service-swagger_json.txt)

**Comment by ganqqwerty** [comment]
It looks like your json file is not valid, check it with the validator here: https://bigstickcarpet.com/swagger-parser/www/index.html
