### ISSUE TITLE
Migrating the code to TypeScript

### ISSUE THREAD

**Issue by ganqqwerty** [cyclosproject/ng-swagger-gen#65]
We generate TS but our code itself is mostly ES5 javascript. Would you mind if I migrate the code to TypeScript? Specifying the return value types and the parameters types can beneficial for people who wants to add functionality, and TS modules work very nicely for decomposing the code by files (thus having less merge conflicts).

**Comment by luisfpg** [comment]
This is a nice thing, and something I was thinking about.
Will mature the idea, and see how this fits into the idea of multiple generation modules. See https://github.com/cyclosproject/ng-swagger-gen/issues/64#issuecomment-394344883

**Comment by luisfpg** [comment]
Sorry, this never got into ng-swagger-gen, and there's no viable resources to implement it.
The https://github.com/cyclosproject/ng-openapi-gen/ was already written in TypeScript and it will receive most of the resources in the future, though bug fixes will still be done in ng-swagger-gen.
