### ISSUE TITLE
Generate service mocks/stubs

### ISSUE THREAD

**Issue by ganqqwerty** [cyclosproject/ng-swagger-gen#66]
We have enough data to generate the mocks of the services, be it Jasmine spies or vanilla js mocks. These mocked services can either return the values mentioned in example section, or they can generate the random values. 

Each time we test a component that depends on http service, we need mock it manually and to take care of the consistency between the mock and the real service. Here ng-swagger-gen can take care of this. 

I can try to implement this for Jasmine and add new option parameter: `generateServiceMocks`. I think the mocks of the services should be located in the same directory as the real services. As for Jest, I don't think that we will need anything more than another mustache template there.

**Comment by itslenny** [comment]
While this would be nice an alternative for the time being is to create a factory that creates a mock on the fly using the methods defined in the ApiService.

```typescript
export type MockApiService = jasmine.SpyObj<ApiService>;
export function getApiServiceMock(): MockApiService {

  let service = new ApiService(<any>{}, <any>{});
  const serviceMethods = Object.keys(Object.getPrototypeOf(service))
    .filter(method => !method.endsWith('Response') && method !== 'constructor');

  const instance: MockApiService = jasmine.createSpyObj('ApiService', serviceMethods);

  serviceMethods.forEach(method => instance[method].and.returnValue(Observable.of({})));
  return instance;
}
```

**Comment by luisfpg** [comment]
There are no viable resources to implement an official support, but @itslenny 's suggestion should be ok.
Closing.
