### ISSUE TITLE
why angular>=6.0.0 in peer dependecies

### ISSUE THREAD

**Issue by ganqqwerty** [cyclosproject/ng-swagger-gen#69]
I looked at package.json and I have a question. Is angular 6+ and rx 6+ really required for ng-swagger-gen? Is seems to me that it works even with angular 2+.

**Comment by luisfpg** [comment]
Because the generated code requires Angular 6.
The generator itself doesn't require Angular / RxJS at all.
It is expressed as a peer dependency to make it clear that it is a "runtime" dependency.
