### ISSUE TITLE
Add ability to clean operationid's

### ISSUE THREAD

**Issue by niemyjski** [cyclosproject/ng-swagger-gen#70]
It would be great if I could specify a regex or function to clean operationid's. We are working on cleaning it up more server side but we have a versioned api and so our operation id's are versioned and also contain the controllers name in it which is redundant. Is there a good way to do this without forking the templates?

**Comment by luisfpg** [comment]
There's currently no way to map operation ids to some other name.
Maybe you could pre-process your swagger descriptor to replace them before generating?
It shouldn't be too hard to do.

**Comment by niemyjski** [comment]
I'd rather point to a live api and have a regex or something defined in the
options to remove prefixes :)

**Comment by luisfpg** [comment]
Yes, but that is a corner case.
None of the generators on http://generator.swagger.io/ will offer a way to change the operation ids.
I don't think this is a requirement that fits the goals of ng-swagger-gen.
Of course, feel free to fork the project, but just changing the templates wouldn't probably be enough: you'd need to patch `ng-swagger-gen.js` to modify the operation ids.
