### ISSUE TITLE
How to login with a session token

### ISSUE THREAD

**Issue by JasoonS** [cyclosproject/ng-swagger-gen#72]
This is a general cyclos question, not specific to this repo.

Is it possible to use a session token instead of using `'Authorization': 'Basic '+<username>+':'+<password>`?

I'm writing this in a pure nodejs back-end. (So not angular, I just don't know where else to ask the question)

What I have tried already:
First I get a session token via the: `/api/auth/session`
Lets say I get the token: `ghv8CKB9UpB2JoSOpazNJtnnPr9RBCSG` back.
Then I've tried setting all sorts of headers such as `'Session': 'ghv8CKB9UpB2JoSOpazNJtnnPr9RBCSG'` in my example. (the docs in this repo imply that this should work?)

Reading the readme of this repo implies that I can use session tokens? But this wiki page for example doesn't mention anything about session tokens: https://wiki3.cyclos.org/index.php/REST_Web_services

Here is my code to make this concrete:
```javascript
const credentials = username+':'+password
const base64Credentials = Buffer.from(credentials).toString('base64')
const uri = config.apiServerAddress + '/api/auth/session'
const options = {
  method: 'POST',
  headers: {
    'content-type': 'application/x-www-form-urlencoded',
    'Authorization': 'Basic '+base64Credentials
  }
}
const response = await (await fetch(uri, options)).json()
console.log('Session', response.sessionToken)
const uri2 = config.apiServerAddress + '/api/accounts/data-for-user-balances'
const options2 = {
  method: 'GET',
  headers: {
    'content-type': 'application/x-www-form-urlencoded',
    // WHAT DO I PUT HERE?
    // 'Authorization': 'Basic '+base64Credentials
    // 'Cookie': 'Session-Token='+response.sessionToken
    // 'Session-Prefix': response.sessionToken
    // 'Session': response.sessionToken
  }
}
const response2 = await (await fetch(uri2, options2)).json()
console.log('result:', JSON.stringify(response2, null, 2))
```

When run the above code produces:
```
Session ghv8CKB9UpB2JoSOpazNJtnnPr9RBCSG
result: {
  "code": "missingAuthorization"
}
```

Just using the `'Authorization': 'Basic '+<username>+':'+<password>` header just works. Please help me. I refuse to believe that users are expected to send their username and password as plaintext in every request.

Thanks!

**Comment by luisfpg** [comment]
Actually, the correct place to ask this would have been the [Cyclos forums](https://forum.cyclos.org/).
The correct header to pass is `Session-Token`.
You can just navigate to `<your_cyclos_url>/api` to get an interactive documentation of the available web services, and allowed authentication modes.
PS: you have linked the Cyclos 3 wiki. There's a wiki for Cyclos 4 at https://wiki4.cyclos.org/index.php?title=Main_Page.
