### ISSUE TITLE
Code generation problem with full name reference  

### ISSUE THREAD

**Issue by muhammadarshad** [cyclosproject/ng-swagger-gen#75]
I have this swagger doc (partial ) 
```json
"/api/v1/account/login": {
      "post": {
        "tags": [ "Account" ],
        "operationId": "Login",
        "consumes": [ "application/json", "text/json", "application/xml", "text/xml", "application/x-www-form-urlencoded" ],
        "produces": [ "application/json", "text/json", "application/xml", "text/xml" ],
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/API.Models.CredentialsArgument" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "$ref": "#/definitions/API.Models.Response[API.Security.Models.IUser]" }
          }
        },
        "deprecated": false
      }
    }
```
and models generated like this (file name : api.models-.credentials-argument)
```typescript
/* tslint:disable */
export interface API.Models.CredentialsArgument {
  username?: string;
  password?: string;
}
```
I am using .net and model name are based on namespace. I have configured swagger to use full type name so i can use same name model with different namespace.
So there should be a way to handle "."

Suggestion:
If we could able to implement namespaces in code generation. Like if we found "." schema so rather then generation exact same name we split this into

**Comment by luisfpg** [comment]
That would be a part of the problem, because I see definitions such as API.Models.Response[API.Security.Models.IUser], which wouldn't be supported anyhow, as swagger defines no type arguments (generics).
Also, I think that exporting namespaces could actually make things worst in some cases. To me it would be more natural to generate models in subpaths, such as `models/a/b/c.ts`, instead of generating a `models/a.b.c.ts` that exports a full namespace `a.b.c`.
So one would do things like:
```typescript
import { C } from 'app/api/models/a/b/c';
const c = new C();
```
instead of
```typescript
import { a } from 'app/api/models/a.b.c';
const c = new a.b.C();
```

**Comment by plaetzchen79** [comment]
I have similar question:
Is it possible to remove the dots?
https://editor.swagger.io/ is doing is with C# namespaces.
Resulting in huge names - but basically it  works and i can compile

**Comment by luisfpg** [comment]
With issue #78, we now handle each invalid character in names as a separator, so, with the new releases, the generated would models would be, for example, `APIModelsCredentialsArgument`.
All models are stored in the same folder, but at least, as @plaetzchen79 suggested, there are no compilation errors.
