### ISSUE TITLE
XXX Response should be private

### ISSUE THREAD

**Issue by JohnGalt1717** [cyclosproject/ng-swagger-gen#76]
On the generated services the Responses should be private because they shouldn't be accessed directly.

The other members generated from the Operations should be public.

**Comment by luisfpg** [comment]
In many cases it is important to access the response headers.
That's why those methods have to be public.

**Comment by luisfpg** [comment]
For example, it is standard on searches to return headers such as whether this is the last page, or returning a total count for pagination.
Also, reading the `Location` header for created elements is also a common practice.
Of course we can accept a PR for adding the configuration option.
Alternatively, you can use a custom templates folder, customizing the `operationResponse.mustache` file, and adding `private ` before the first `{{operationName}}` occurrence.

**Comment by JohnGalt1717** [comment]
Ah, for people that don't like oData for some strange reason and insist on reinventing the wheel instead of using standards.

Ok. I'll live for now. Thanks for the suggestion.
