### ISSUE TITLE
Add an option to control how to sort operation parameters

### ISSUE THREAD

**Issue by sschoeb** [cyclosproject/ng-swagger-gen#79]
ng-swagger-gen does sort the operation-parameters first by "required" and then by "name". 

We do not want to resort the Parameters. It would be nice to have an option do disable this functionality.

**Comment by luisfpg** [comment]
In TypeScript it is required to that optional function / method parameters come last.
For example, this compiles:
```typescript
function a(x, y?) {}
```
but this doesn't:
```typescript
function a(x?, y) {}
```

**Comment by sschoeb** [comment]
This is true, but...

What happens now is that you can create a clean API with a usefull order of parameters like so:

doSomething1(userId, page, numberOfItemsPerPage)
doSomething2(userId, action)
doSomething3(userId, zone)

This ends up in a client API like:
doSomething1(numberOfItemsPerPage, page, userId)
doSomething2(action, userId)
doSomething3(userId, zone)

As you can see, this "reordering" somehow messes up the client and makes it not intuitive to use.

An option do disable this "break my API-Design"-behaviour would be nice. I can totally life with the fact, that a wrong optional Parameter order would break my build. But this should be fixed on the API itself...

**Comment by luisfpg** [comment]
True. Parameters shouldn't be sorted by name.
This should be fixed.
