### ISSUE TITLE
Command line output arguments to override value in config file

### ISSUE THREAD

**Issue by wernerva** [cyclosproject/ng-swagger-gen#80]
Hi there,

I would find it valuable if I could override the output directory configured in the  ng-swagger-gen.json config file by just passing the output argument in the command line.

**Comment by luisfpg** [comment]
This was never implemented due to the lack of resources.
The current state is ok for most projects.
https://github.com/cyclosproject/ng-openapi-gen was already developed with this in mind, and works as suggested.
