### ISSUE TITLE
api.module.ts template issue

### ISSUE THREAD

**Issue by egandro** [cyclosproject/ng-swagger-gen#82]
Please sort the headers in the api.module.ts template

     import { NgModule } from '@angular/core';
     import { HttpClientModule } from '@angular/common/http';
     import { ApiConfiguration } from './api-configuration';

to

     import { HttpClientModule } from '@angular/common/http';
     import { NgModule } from '@angular/core';
     import { ApiConfiguration } from './api-configuration';

or the tslint will complain

... or add /* tslint:disable */

Thx.

**Comment by egandro** [comment]
Why does this problem exists?

in tslint.json I have

    "rules": {
      "ordered-imports": [
        true,
        {
          "module-source-path": "basename",
          "import-sources-order": "lowercase-last",
          "named-imports-order": "lowercase-first"
        }
      ],
    ...

This is my (semi) hack for fixing this.

in package.json

      "createapi": "ng-swagger-gen --config ng-swagger-gen.json && node apigen-fix.js"

    

apigen-fix.js

      // ng-swagger-gen has a broken template for the "api.module.ts" file
      // we will just add an ignore to it
      const fs = require('fs');
      const fileName = './src/app/apiweb/api.module.ts';
      // read + patch
      let content = fs.readFileSync(fileName, 'utf8');
      content = '/* tslint:disable */\n' + content;

      // write
      fs.writeFileSync(fileName, content, 'utf8');

      console.log('patching "api.module.ts" tslint issue done.');

**Comment by luisfpg** [comment]
I don't have any tslint complaints on `api.module.ts` using a default `tslint.json` generated by Angular cli.
Anyway, it doesn't hurt to add `/* tslint:disable */` at the beginning of the line.
Will be done in the next release.
Until then, an alternative is to copy the templates to some other folder, indicate that in `ng-swagger-gen.json` (in `templates` property) and add modify the the `apiModule.mustache` file.
