### ISSUE TITLE
An operationId that contains a dash generate invalid service methods

### ISSUE THREAD

**Issue by grizzlyjere** [cyclosproject/ng-swagger-gen#85]
Appears to be a similar situation as issue #78.  If swagger.json has an operationId with a dash, invalid typescript is generated and the project can't compile

Example:
Swagger.json:
`"operationId": "ApiEmployee-ManagersGet"`

employee-manager.service.ts:
`ApiEmployee-ManagersGet(): Observable<Array<EmployeeManagerResource>> {`

My swagger file is generated from a .Net add-in, so perhaps it shouldn't be adding dashes to the operationId in the first place, but I'm not super familiar with the swagger spec.

**Comment by luisfpg** [comment]
Fixed in 1.2.2
