### ISSUE TITLE
Generated code doesn't compile if any parameter is named 'filter' or 'map'

### ISSUE THREAD

**Issue by iprayforwaves** [cyclosproject/ng-swagger-gen#94]
The generated services cause compile errors, for example:

src/app/client/services/category.service.ts(618,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'String' has no compatible call signatures

**Comment by luisfpg** [comment]
Can you share a snippet of the swagger source that generated this error?

**Comment by rodzappa** [comment]
Hi all, same problem here! 

ERROR in src/app/APIRestClient/services/produto-resource.service.ts(47,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'String' has no compatible call signatures.

Bellow, part of swagger.json correlated whit the problem:
[swagger.json.gz](https://github.com/cyclosproject/ng-swagger-gen/files/2377197/swagger.json.gz)



"/api/produtos": {
      "get": {
        "tags": [
          "produto-resource"
        ],
        "summary": "getAllProdutos",
        "operationId": "getAllProdutosUsingGET",
        "produces": [
          "*/*"
        ],
        "parameters": [
          {
            "name": "filter",
            "in": "query",
            "description": "filter",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Produto"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      },

**Comment by rodzappa** [comment]
This is the problematic generated code:

```
getAllProdutosUsingGETResponse(filter?: string): Observable<HttpResponse<Array<Produto>>> {
    let __params = this.newParams();
    let __headers = new HttpHeaders();
    let __body: any = null;
    if (filter != null) __params = __params.set('filter', filter.toString());
    let req = new HttpRequest<any>(
      'GET',
      this.rootUrl + `/api/produtos`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });

    return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),  // <-- Error here!
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: Array<Produto> = null;
        _body = _resp.body as Array<Produto>;
        return _resp.clone({body: _body}) as HttpResponse<Array<Produto>>;
      })
    );
  }
```

**Comment by rodzappa** [comment]
I understood now. "filter" is a reserved name and the code can't use a request parameter named "filter". The obvious way to correct this issue is not naming any request parameter as a reserved name like "filter".

The code bellow is working well:

```
getAllProdutosUsingGETResponse(otherName?: string): Observable<HttpResponse<Array<Produto>>> {
    let __params = this.newParams();
    let __headers = new HttpHeaders();
    let __body: any = null;
    if (otherName != null) __params = __params.set('filtro', otherName.toString());
    let req = new HttpRequest<any>(
      'GET',
      this.rootUrl + `/api/produtos`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });

    return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: Array<Produto> = null;
        _body = _resp.body as Array<Produto>;
        return _resp.clone({body: _body}) as HttpResponse<Array<Produto>>;
      })
    );
  }
```
