### ISSUE TITLE
Feature Request: x-nullable

### ISSUE THREAD

**Issue by aersamkull** [cyclosproject/ng-swagger-gen#97]
In Swagger 2.0 it is not really possible to mark a property/parameter as nullable. However in a strict-null environment this is often something good to indicate. Therefore, ng-swagger-gen should support x-nullable which is supported by various tools already. 
The other option would be support for Open API 3.0 which contains a nullable property.

Parameter:
![image](https://user-images.githubusercontent.com/5270024/45607720-a0099c80-ba4e-11e8-96be-be8ffd6ce9d4.png)

Model:
![image](https://user-images.githubusercontent.com/5270024/45607748-bf082e80-ba4e-11e8-83fd-ba665438f46f.png)

**Comment by luisfpg** [comment]
This should be the original issue regarding this, but #114 was created also.
Closing this one as duplicate.
